### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by cjwelborn** [Syntaf/MazeSolver#2]
A small compile error using `make`:

```
In file included from ~/MazeSolver/src/mazesolve/mazeGen.cpp:6:0:
~/clones/MazeSolver/src/mazesolve/astar.hpp:74:50: error: ‘>>’ should be ‘> >’ within a nested template argument list
                      std::vector< std::vector<int>> map)
                                                  ^
make[2]: *** [CMakeFiles/MazeSolver.dir/src/mazesolve/mazeGen.cpp.o] Error 1
make[1]: *** [CMakeFiles/MazeSolver.dir/all] Error 2
make: *** [all] Error 2
```

..Changed `>>` to `> >` in `astar.hpp` and it was fine. Sorry I don't have a pull request to go with this.

**Comment by Syntaf** [comment]
Whoops, this is because I compiled using C++11 . C++0x allows >> to be used in nested templates while pre 11 does not. I may change this just for compatibility . thanks!

**Comment by cjwelborn** [comment]
Oh i see. I think that feature can be enabled automatically using `target_compile_features` with `cmake`, by enabling one of the `CMAKE_CXX_KNOWN_FEATURES` (`cxx_right_angle_brackets`). `cmake` will use the correct standard when a feature requires it.

[Example in the CMake docs](http://www.cmake.org/cmake/help/v3.1/manual/cmake-compile-features.7.html#compile-feature-requirements)
